### ISSUE TITLE
You have exceeded the API usage limit. Please limit the usage to 1 request/minute.

### ISSUE THREAD

**Issue by AJFeng** [outbreak-info/R-outbreak-info#101]
Is there any way to run a few hundred requests?

I am using getPrevalence( function), got the following error:
You have exceeded the API usage limit. Please limit the usage to 1 request/minute.

**Comment by flaneuse** [comment]
@AJFeng If you're running a few hundred requests, we suggest you add a pause between calls to avoid the throttling.  You can add a `Sys.sleep(pause_time)` within your loop to add a `pause_time` pause between requests.
