### ISSUE TITLE
Issue with authenticateUser(): A gpsapi error occured on the gps_authenticate page

### ISSUE THREAD

**Issue by TKMarkCheng** [outbreak-info/R-outbreak-info#103]
`outbreakinfo::authenticateUser()` brings me to the user authentication page on GISAID, but returns the error message below when entered with the correct username and password that can otherwise be used to log in normally via the GISAID websites.

![image](https://user-images.githubusercontent.com/89597443/222016955-df19f1e4-7ae5-4a52-b8fb-8a958ee7f37b.png)

**Comment by TKMarkCheng** [comment]
@flaneuse @malkuzweny sorry to tag but am very excited to start using the R package! Would be great if I can get some pointers especially if this issue had been encountered before.

**Comment by flaneuse** [comment]
Hi @TKMarkCheng -- thanks for checking back in. We're sorting through an issue with the API and hopefully will update you soon when it's working. Thanks for your interest in the package and sorry for the inconvenience!

**Comment by TKMarkCheng** [comment]
No worries @flaneuse and super grateful for the prompt reply! Does this mean this is a global problem and not specific to my machine/environment?

**Comment by flaneuse** [comment]
Yes, it's definitely not you-- the error is on our side.

**Comment by flaneuse** [comment]
@TKMarkCheng -- this should be fixed now.  Please let us know if you run into other problems. Thanks!

**Comment by TKMarkCheng** [comment]
Can confirm it's functional on my end too. Thank you so much for the swift response!
