### ISSUE TITLE
Issues with GetPrevalence() when seraching for ONLY mutations

### ISSUE THREAD

**Issue by TKMarkCheng** [outbreak-info/R-outbreak-info#104]
GetPrevalence() returns Malformed Token Error.
The example search of E484K within [getPrevalence.R](https://github.com/outbreak-info/R-outbreak-info/blob/506e0ee313da96acd171f51b482edb4a6e7eb06a/R/getPrevalence.R) returns the following error.
```{r}
> E484K_prevalence = getPrevalence(mutation = c("S:E484K"))
Retrieving data... 
Warning: Malformed token. Please reauthenticate by calling the authenticateUser() function.
Error in invokeRestart("muffleWarning") : 
  no 'restart' 'muffleWarning' found
```
Adding a search pangolin_lineage rescues this behavior (i.e. `getPrevalence(pangolin_lineage = "P.1", mutation = c("S:E484K"))`, but 1) Searching for multiple mutations; or 2) adding a location does not fix the issue.

**Comment by pengwei1993** [comment]
so how solve this problem? If I want to search for E484K mutation from all lineages rather than one lineage

**Comment by pengwei1993** [comment]
> so how solve this problem? If I want to search for E484K mutation from all lineages rather than one lineage

one month ago, I can search for E484K mutation from all lineages,now It's wrong

**Comment by TKMarkCheng** [comment]
@flaneuse this is a relatively debilitating error for the genomics API, and it seems to be a problem on the outbreak.info website itself as well. I'm gusesing this is a sever or an API problem?

**Comment by pengwei1993** [comment]
您好，来信已收到，我会尽快回复。 尽快给您回复。

**Comment by flaneuse** [comment]
@TKMarkCheng thanks for bringing this to our attention.  you're correct: it was a parameter incorrectly set on the API.  Fixed in https://github.com/outbreak-info/outbreak.api/pull/86

**Comment by pengwei1993** [comment]
So? This problem could be solved?

**Comment by TKMarkCheng** [comment]
Thank you @flaneuse for your timely reply and the team for fixing the issue!
@pengwei1993 it would be nice if you can be more courteous and more specific when raising issues on GitHub, but yes, the outbreak.info team has kindly fixed the issue as of today (18th March 2023).
```
E484K_prevalence = getPrevalence(mutation=c("S:E484K"))
E484K_prevalence
plotPrevalenceOverTime(E484K_prevalence)
```
yields the following figure.
![image](https://user-images.githubusercontent.com/89597443/226076888-22364e28-d590-40ba-adcf-5c7ef5503d34.png)

**Comment by pengwei1993** [comment]
great, thank you







&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "outbreak-info/R-outbreak-info"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 上午9:49
***@***.***&gt;;
抄送:&nbsp;"Li ***@***.******@***.***&gt;;
主题:&nbsp;Re: [outbreak-info/R-outbreak-info] Issues with GetPrevalence() when seraching for ONLY mutations (Issue #104)





 
Thank you @flaneuse for your timely reply and the team for fixing the issue!
 @pengwei1993 it would be nice if you can be more courteous and more specific when raising issues on GitHub, but yes, the outbreak.info team has kindly fixed the issue as of today (18th March 2023).
 E484K_prevalence = getPrevalence(mutation=c("S:E484K")) E484K_prevalence plotPrevalenceOverTime(E484K_prevalence)  
yields the following figure.
