### ISSUE TITLE
Vignette `getLocationData` function is broken

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#15]
From https://outbreak-info.github.io/R-outbreak-info/outbreakvignette.html, using version 0.2.0 built on 3 November 2020:

`df=getLocationData(c("Texas", "Brazil", "San Diego County"))`

-->
```
Error in getLocationData(c("Texas", "Brazil", "San Diego County")) : 
  could not find function "getLocationData"
```

**Comment by malkuzweny** [comment]
getLocationData function no longer exists, example will be removed when vignette is updated

**Comment by malkuzweny** [comment]
Updated vignette and fixed bug
