### ISSUE TITLE
Vignette `getAdmn2ByState` function is broken

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#16]
`getAdmn2ByState(“California”) `
 -->
```
1] "Retrieving data..."
 1 records retrieved

Error in rbind_pages(results) : 
  all(vapply(pages, is.data.frame, logical(1))) is not TRUE
```

**Comment by gkarthik** [comment]
`getAdmn2ByState("California")` also uses `country_name`  on [L21](https://github.com/outbreak-info/R-outbreak-info/blob/master/outbreakinfo/R/getAdmn2ByState.R#L21) should be `state_name`
