### ISSUE TITLE
getEpiData function is broken

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#18]
`getEpiData(name="United States of America", date=2020-07-01, mostRecent=T)` example from the help documentiation is broken.

1. Need to translate `mostRecent` argument TRUE / FALSE into ES-compatible representations of booleans (`true`, `false`)
2. Fixing that string leads to an rbind err:
```
getEpiData(name="United States of America", date=2020-07-01, mostRecent='true')

[1] "Retrieving data..."
 1 records retrieved

Error in rbind_pages(results) : 
  all(vapply(pages, is.data.frame, logical(1))) is not TRUE
```

**Comment by gkarthik** [comment]
Thanks! Should be fixed after 4f1442216b903f78390321381163d4c15b2f39a2. Also corrected faulty example, `getEpiData(name="United States of America", date=2020-07-01, mostRecent='true')` will always return 0 hits.
