### ISSUE TITLE
Improve helper text displayed to user

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#20]
Call: `county_df=getAdmn2ByCountry()`

* The counter says things like `144 records retrieved`; do you actually mean 14,400 records?  Would suggest changing language to either something like "query" or multiplying by 1000.
* It'd be helpful to grab the number of results so you have an idea of how far you are into the function call (e.g. 14,400 out of 68,000)
* Would be nice to add a newline after "X records are retrieved".  When there's an error, they get pasted together.
* Might also be useful to display the estimated time remaining in the function. see `progress` package: https://dplyr.tidyverse.org/reference/progress_estimated.html

**Comment by gkarthik** [comment]
To create the progress bar, we need the total number of results which can be obtained from the `total` field in the object returned by the query,
```
{
    "_scroll_id": "DnF1ZXJ5VGhlbkZldGNoAwAAAAAAlEHcFmVWUk5HRkRKUllPdmg4VkNhS1hSWncAAAAAAJRB3hZlVlJOR0ZESlJZT3ZoOFZDYUtYUlp3AAAAAACUQd0WZVZSTkdGREpSWU92aDhWQ2FLWFJadw==",
    "took": 180,
    "total": 13312,
    "max_score": 3.9468555
...
}
```
