### ISSUE TITLE
getSeqCounts broken (?)

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#31]
<img width="529" alt="Screen Shot 2021-05-12 at 4 25 08 PM" src="https://user-images.githubusercontent.com/8041065/118046228-a60ac500-b33e-11eb-95d1-a43ada5d2df8.png">

**Comment by malkuzweny** [comment]
I removed and reinstalled the package on my end and getSeqCounts works for me. Are the other functions broken for you too?

**Comment by flaneuse** [comment]
Still broken after removing and reinstalling?  Going through the other functions today and tomorrow.
![Uploading Screen Shot 2021-05-12 at 5.12.06 PM.png…]()

**Comment by flaneuse** [comment]
<img width="744" alt="Screen Shot 2021-05-12 at 5 12 06 PM" src="https://user-images.githubusercontent.com/8041065/118050882-b8d4c800-b345-11eb-9c8d-daee5a33415e.png">

**Comment by malkuzweny** [comment]
No, and even if I had we should be using the same function now (my environment is cleared and I just reinstalled).

**Comment by flaneuse** [comment]
Need to add `plyr` as a dependency in the package requirements, or else `getISO3_genomic` returns an error: `"Error : Required package plyr not found. Please run: install.packages('plyr')\n"`
