### ISSUE TITLE
Add a nicer error message for slow internet connections

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#35]
I think my internet flaked out, so I got a connection time out message.  Might be nice to catch timeout errors, esp. if they happen when the API is down for maintenance / data update.

![Uploading Screen Shot 2021-05-13 at 2.14.59 PM.png…]()

**Comment by malkuzweny** [comment]
Can you reupload the screenshot for this?

**Comment by flaneuse** [comment]
Sorry!
<img width="727" alt="Screen Shot 2021-05-13 at 2 14 59 PM" src="https://user-images.githubusercontent.com/8041065/118278398-977ff300-b48f-11eb-8174-fe092d4da0dc.png">

**Comment by flaneuse** [comment]
You can replicate a similar error by turning off your wifi and then trying to call a function, which will give this error: `Error in open.connection(con, "rb") : Could not resolve host: api.outbreak.info`
