### ISSUE TITLE
Add ggtitle to plotPrevalenceByLocation

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#36]
See also #32

**Comment by malkuzweny** [comment]
How is this issue different from #32 ?

**Comment by flaneuse** [comment]
Whoops, I must have copied the wrong function name.  There's another plotting function that could use a title, lmk if you can't figure out which one.

**Comment by malkuzweny** [comment]
Got it! I think it's `plotAllLineagesByLocation`. Thank you!
