### ISSUE TITLE
Investigate rpy2 package error

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#44]
@watronfire noticed a potential connection issue when trying to run the package through `rpy2`
![image](https://user-images.githubusercontent.com/8041065/134427197-79949373-45ff-4ab3-bd27-3e70b5baad34.png)

Function call: `countries <- getAdmn0()`

**Comment by malkuzweny** [comment]
@watronfire Do the other functions work in `rpy2`?
