### ISSUE TITLE
Bad error for "location not found"

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/R-outbreak-info#54]
getAllLineagesByLocation(location = "US")
```
Retrieving data... 
invalid subscript type 'list'
 Error in value[[3L]](cond) : 
  Could not connect to API. Please check internet connection and try again. 
  ```

Ideal error: something like `Location not found.  Did you mean "United States"?`

**Comment by gkarthik** [comment]
Fix in https://github.com/outbreak-info/R-outbreak-info/commit/8fdce3646dcd1d8d5e7f69898d4e3ebe8b17ed3f. 
`Location not found` should be logged.
