### ISSUE TITLE
Is this manual still accurate?

### ISSUE THREAD

**Issue by starlagthornhill** [outbreak-info/R-outbreak-info#79]
https://outbreak-info.github.io/R-outbreak-info/articles/outbreakinfo.html

The install link gives a 404 error. I installed instead with the line from the readme here, `devtools::install_github("outbreak-info/R-outbreak-info/outbreakinfo") ` which installed, except many of the functions listed in the manual don't work: 

```
authenticateUser()
getPrevalence()
plotPrevalenceOverTime()
getCumulativeBySubadmin()
getMutationsByLineage()
plotMutationHeatmap()
getResourcesData()
```

all produce a "could not find function" error. 

I do have the package loaded (I checked multiple times, and the `getEpiData()` function works)

**Comment by flaneuse** [comment]
Thanks @starlagthornhill for pointing this out.  We're in the process of releasing a new version of the R package which will give access to the SARS-CoV-2 variant data for authorized GISAID users.  As a result, the documentation website is ahead of the actual package. 

If you're interested in beta testing the package before release in December, that would be fantastic -- ping me at lhughes@scripps.edu and we'll send you documentation on how to install the package.

**Comment by rpscruz** [comment]
Hullo @flaneuse ! Encountered these issues too. May I ask if there might be a target release date this December 2021? Thanks!

**Comment by khyox** [comment]
Hi @flaneuse and @gkarthik! I see that your team has been working very hard on the dev branch and it's quite ahead in commits! Are you planning to merge into the main brach anytime soon? Thank you so much!

**Comment by gkarthik** [comment]
Hi @khyox ! There are still a few issues I need to fix and we will be merging the `dev` into `master` by the end of this month.

**Comment by khyox** [comment]
Sounds great, looking forward to that! Thank you very much, @gkarthik!

**Comment by flaneuse** [comment]
Hi @khyox @rpscruz @starlagthornhill -- the `main` branch of the package is now up-to-date with the latest version of the R package.  Please let us know if you spot additional issues.  Thanks!
