### ISSUE TITLE
incorrect code for package installation on the website. 

### ISSUE THREAD

**Issue by eycramer** [outbreak-info/R-outbreak-info#83]
Hi - just to let you know, the code for installing the package on the main website has the wrong link (see screenshot). 

I believe it should be `devtools::install_github("outbreak-info/R-outbreak-info/outbreakinfo")`

![image](https://user-images.githubusercontent.com/60321389/149349263-41c13c70-5f15-4ed0-bbff-554e0aace735.png)

**Comment by flaneuse** [comment]
Thanks! The main branch was referring to an outdated version of the code.  It has since been updated and the documentation is accurate.
