### ISSUE TITLE
Unable to Install - 

### ISSUE THREAD

**Issue by alexlundberg** [outbreak-info/R-outbreak-info#88]
Is the installation still working correctly? When I try to install outbreak.info, I get a namespaceExport() error, and the installation fails. Here's a screenshot:

![image](https://user-images.githubusercontent.com/89858947/173633403-e1add947-9711-4e83-9284-3b38bfd43406.png)

**Comment by flaneuse** [comment]
@alexlundberg: @gkarthik and I weren't able to replicate your error on our machines, including on a fresh R instance.  Are there any other details you can provide us?  Thanks.

**Comment by alexlundberg** [comment]
I just got it to work. For some reason, Windows 10 refused to delete a certain folder, which caused a confusion in R libraries. After running chkdsk /f and doing a clean installation of R, I got the API up and running.

Many thanks!

**Comment by flaneuse** [comment]
Glad you hear you got it resolved!
