### ISSUE TITLE
Can locationName be more "specific" and identify regions?

### ISSUE THREAD

**Issue by carlottaolivero** [outbreak-info/R-outbreak-info#98]
Hi,
I have tryed to get lineage prevalence graph for 
> locationName = "Italy" 
and it worked.

Then I have tryed to get the graph for Piedmont that is an Italian region.
> locationName = "Italy/Piedmont" 
 and the result is 
**Could not find location 
NULL**

I have also tryed "Europe/Italy/Piedmont", and only "Piedmont" but it is not working.

Is it possible to change the location and go more deeply into sub-location?

Many thanks,
Carlotta

**Comment by malkuzweny** [comment]
Hello Carlotta,

While it is possible to pull data for a specific region, we do not currently have data at the regional level for Italy. Sorry about that!

**Comment by carlottaolivero** [comment]
Thank you anyway!
